### PR TITLE
Add nunjucks support

### PR DESCRIPTION
**Pull request by mariosant**
It would be nice to have support for nunjucks template engine. This PR could be a good starting point for supporting it.

Happy new year! :smile:

### CODE REVIEW

**Comment by d3x7r0** [comment]
I'm just adding my +1 to this pull request. I was actually going to do it myself :)

**Comment by howardroark** [comment]
Hey @mariosant did you end up getting the globals object into the template context?  I merged your pull request into the latest branch to try it out.  Got nunjucks to function but couldn't find any of the global object variables defined in `harp.json`.

Either way I really want this!  To me jade isn't a template language, and I have to fight it a lot.  EJS conflicts because I use backbonejs and inline underscore templates.  Don't want them getting gobbled up :P 

Plus with Twig, Django, Jinja and nunjucks all using the same style... It's just economics!

**Comment by mariosant** [comment]
Hey! I didn't think this had any future, so I didn't work on this any more.

Since you are interested in this, I can continue this work.

**Comment by howardroark** [comment]
That would be fantastic!

I can verify that it merges nicely and runs without errors with the HEAD of this repo.  Though I ended up merging it a few commits back in time.  The latest update has a bunch of browserify work that causes all js files to return 404.  Must be a WIP feature or they are introducing a breaking change.  You can see here where I merged... https://github.com/howardroark/terraform/commits/master

**Comment by mariosant** [comment]
Great to hear that @howardroark! I will find some time to work on this. It would be really helpful to build a checklist or something for things that should be implemented, like accessing global object var from `harp.json`.

**Comment by howardroark** [comment]
- [ ] Introduce the `global` object to the context of all nunjucks templates

This is #1 ;)

Right now there is a pattern of automatically using `_layout` as the parent template for jade and ejs. I don't think that would be required for nunjucks since the jinja style templates already "extend"... so it will be normal for users to extend from `_layout` themselves.

**Comment by mariosant** [comment]
Cool! I will let you know how it goes.

**Comment by howardroark** [comment]
To add to this... I think this totally does have a future!  I think it is a very pragmatic choice for a template engine.  It is just foreign to the node community, which is why it likely went overlooked :P

**Comment by mariosant** [comment]
Hey @howardroark, there is a wierd situation here. I have deleted my personal repo, where the PR came from. Any ideas how to deal with it?

**Comment by howardroark** [comment]
Yup, that is exactly how I got the PR code :)

**Comment by mariosant** [comment]
Hey @howardroark, I've managed to bring my PR up to date. I am working on bringing the global context to nunjucks now, but I am a little confused.
Would you like to setup a gitter room, so we can chat about it?

**Comment by mariosant** [comment]
@howardroark, I am closing this one and opening a new PR. Please follow me at #126 .

**Pull request closed without merging**
