### PR TITLE
Updating jade version to 1.9.2

### PR DESCRIPTION
**Pull request by najamkhn**
- Updating jade to latest version
- Fixing testcases, removing the deprecated jade syntax for doctype

### CODE REVIEW

**Comment by Spone** [comment]
Hi there! Is something preventing from merging this into master? (except the breaking change in syntax for the doctype). Is there any way to use this branch of terraform in harp without having to fork both projects?
Thanks in advance :)

**Comment by najamkhn** [comment]
@Spone I am willing to fork both the projects if enough people need the change.

**Comment by kennethormandy** [comment]
Hey, thanks for the pull request. To be clear, it’s not actually the case that we don’t want to upgrad Jade—we definitely want to be on the latest version of every preprocessor. We are just cautious about the repercussions of upgrading Jade without any sort of fallback for `!!!` since every app started with `harp init` would have included it for a very long time.

I think we would happy accept a pull request that bumped Jade while dealing with or warning on `!!!`, even if it was just a temp. fix and console logging a deprecation notice. We just don’t want to upgrade and break everyone’s apps (especially if Jade is approaching 2.0 and that might happen again).

It is possible to use `npm shrinkwrap` to get around it in the meantime, I believe. We appreciate the feedback though, and if you’re at all interested in a PR that maintains or mitigates `!!!` support, that would be very interesting to us.

**Comment by najamkhn** [comment]
@kennethormandy I've added the support to show warning for the deprecated syntax of Jade.

**Comment by kennethormandy** [comment]
This is great, thanks @najamkhn. Queued up here #83, @sintaxi and I should be able to talk about it tomorrow.

**Comment by Spone** [comment]
Thanks! :clap:

**Pull request merged**
