### PR TITLE
Adding support to yaml in data

### PR DESCRIPTION
**Pull request by andrematheus**
Hi,

I'm starting to use harp for my site and I wanted to use yaml for metadata instead of json, since I prefer to write yaml files by hand, so I added support for terraform to use yaml files the same way as json files. I've copied the existing json tests, adapted them to yaml and they passed. If you think that would be good for terraform please accept the pull request. Thanks!

### CODE REVIEW

**Comment by c3z** [comment]
+1

**Comment by alexking** [comment]
+1

**Comment by B7th** [comment]
+1

**Comment by Yajo** [comment]
Hi there, this PR has become stale and has conflicts. IMHO you can close it, I opened #141 as a rebase of it.

**Pull request closed without merging**
