### PR TITLE
Update node-sass to 2.0.0-beta

### PR DESCRIPTION
**Pull request by jedfoster**
The version of node-sass currently included in terraform is more than 6 months old; node-sass has improved _immensely_ since then. 2.0.0 includes robust support for Sass maps, which would address [this issue over on Harp](https://github.com/sintaxi/harp/issues/329)

### CODE REVIEW

**Comment by buritica** [comment]
:+1:

**Comment by maxdeviant** [comment]
I just started looking into maps today, would be great if they were supported :+1:

**Comment by kennethormandy** [comment]
Hey, we ended up reverting to Node-sass `v1.x` since v2.0 was causing issues, but I we should be able to bring this back once 2.0 is out of beta. Thanks for the work on it!

**Comment by sintaxi** [comment]
Ok now that node-sass v0.2.1 is released it looks like it builds on node v0.12.0. We should be able to get this in now.

**Pull request merged**
