### PR TITLE
Replacing node-sass with sass, a pure js implementation

### PR DESCRIPTION
**Pull request by icarus-sullivan**

### CODE REVIEW

**Comment by icarus-sullivan** [comment]
Opened this PR as node-sass sometimes locks consumers into certain versions of node. `node-sass` might have wide support across Node versions, but the JS for sure does.

**Comment by sintaxi** [comment]
Thanks @icarus-sullivan! 

I'm definitely on board with this change.  `node-sass` has certainly caused some grief. Are you familiar with the `sass` lib? Is it mature?

**Comment by icarus-sullivan** [comment]
@sintaxi It has been around for 3 years and has over 2 million weekly downloads. https://www.npmjs.com/package/sass

While 3 years is not a long time, I have noticed no issues updating any of my projects to use it. The dev teams seems to be active, and its interoperability with things like webpack and other libs are already in place. I consider it mature, because of its widespread adoption.

**Comment by sintaxi** [comment]
I'm sorry this took so long to implement. This is a really great contribution to this library. I just merged into terraform and cut a new release or harp `v0.33.0` with these changes.

**Pull request merged**
